# SPDX-License-Identifier: MIT

# Main settings
server:
  port:
    4443
  ssl:
    enabled: true # always enabled
    protocol: TLS
    enabled-protocols: TLSv1.2,TLSv1.3

spring:
  messages:
    basename: "i18n/messages"
  profiles:
    group:
      web-server_prod: "ssl-cert-required,oauth2"
      web-server_int: "ssl-cert-required,oauth2,classic-auth-enabled"
      web-server_dev: "ssl-cert-provided,classic-auth-enabled"
      web-server_local: "ssl-cert-provided,classic-auth-enabled,local"
      web-server_test: "test"
      web-server_integrationtest: "ssl-cert-provided,integrationtest-data"
  web:
    resources:
      static-locations: classpath:/static

# Spring Boot Actuators and Metrics
management:
  server:
    port:
      10250
    ssl:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "prometheus,health"
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true