# SPDX-License-Identifier: MIT
# This configuration is used for development and local testing. It uses a self-signed certificate provided by the build.

server:
  ssl:
    key-store-type: 'PKCS12'
    # we use a keystore location which is never tracked by git.
    # see dev-create_localhost_certificate.sh and  dev-ensure_localhost_certificate.sh
    key-store: 'classpath:certificates-untracked/generated-dev-localhost-keystore.p12'
    key-store-password: '123456'
    key-alias: 'tomcat'

webserver:
  sechub:
    server-url: "https://localhost:8443"
    trust-all-certificates: true
