# SPDX-License-Identifier: MIT

apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Chart.Name }}
    labels:
        name: {{ .Chart.Name }}
spec:
    replicas: {{ .Values.replicaCount }}
    selector:
        matchLabels:
            name: {{ .Chart.Name }}
    template:
        metadata:
            labels:
                name: {{ .Chart.Name }}
        spec:
            securityContext:
                runAsUser: 2323 # user id of the gosec user. Set in the Dockerfile.
            containers:
                - name: {{ .Chart.Name }}
                  image: "{{ .Values.image.registry }}:{{ .Values.image.tag }}"
                  env:
                    - name: PDS_START_MODE
                      value: "{{ .Values.pds.startMode }}"
                    - name: ADMIN_USERID
                      value: "{{ .Values.users.admin.id }}"
                    - name: ADMIN_APITOKEN
                      value: "{{ .Values.users.admin.apiToken }}"
                    - name: TECHUSER_USERID
                      value: "{{ .Values.users.technical.id }}"
                    - name: TECHUSER_APITOKEN
                      value: "{{ .Values.users.technical.apiToken }}"
                    - name: ZAP_API_KEY
                      value: "{{ .Values.owaspZap.apiKey }}"
                    - name: PDS_CONFIG_EXECUTE_QUEUE_MAX
                      value: "{{ .Values.pds.config.execute.queueMax }}"
                    - name: PDS_CONFIG_EXECUTE_WORKER_THREAD_COUNT
                      value: "{{ .Values.pds.config.execute.workerThreatCount }}"
                    {{- if .Values.pds.javaDebug.enabled }}
                    - name: JAVA_ENABLE_DEBUG
                      value: "true"
                    {{- end }}
                    {{- if .Values.pds.keepContainerAliveAfterPDSCrashed }}
                    - name: KEEP_CONTAINER_ALIVE_AFTER_PDS_CRASHED
                      value: "true"
                    {{- end }}
                    {{- if .Values.database.postgres.enabled }}
                    - name: POSTGRES_ENABLED
                      value: "true"
                    - name: DATABASE_CONNECTION
                      value: "{{ .Values.database.postgres.connection }}"
                    - name: DATABASE_USERNAME
                      value: "{{ .Values.database.postgres.username }}"
                    - name: DATABASE_PASSWORD
                      value: "{{ .Values.database.postgres.password }}"
                    {{- end }}

                    # Storage priority in order: local, s3, shared volume
                    # Meaning if local is enabled local will be used,
                    # regardless of other storage configurations.
                    {{- if .Values.storage.local.enabled }}
                    - name: SHARED_VOLUME_UPLOAD_DIR
                      value: "/shared_volumes/uploads"
                    {{- else if .Values.storage.s3.enabled }}
                    - name: S3_ENABLED
                      value: "true"
                    - name:  S3_ENDPOINT
                      value: {{ .Values.storage.s3.endpoint }}
                    - name: S3_BUCKETNAME
                      value: {{ .Values.storage.s3.bucketname }}
                    - name: S3_ACCESSKEY
                      value: {{ .Values.storage.s3.accesskey }}
                    - name: S3_SECRETKEY
                      value: {{ .Values.storage.s3.secretkey }}
                    {{- else if .Values.storage.sharedVolume.enabled }}
                    - name: SHARED_VOLUME_UPLOAD_DIR
                      value: "{{ .Values.storage.sharedVolume.upload.dir }}"
                    {{- end}}
                  ports:
                    - containerPort: 8444