# SPDX-License-Identifier: MIT
spring.profiles.include:
 - localserver

sechub.initialadmin:
   userid: sechubadm
   email: sechubadm@example.org    
   apitoken: pseudo-token-development-only
    
logging:
 level:
   com.daimler.sechub: DEBUG
   org.apache.http: WARN
   org.apache.http.headers: WARN
   org.apache.http.wire: WARN
   