# SPDX-License-Identifier: MIT

version: "3"
services:
    pds-owasp-zap-ubuntu:
        build:
            args:
                - BASE_IMAGE=ubuntu:20.04
            context: docker/
            dockerfile: Owasp-Zap-Ubuntu.dockerfile
        container_name: pds-owasp-zap-ubuntu
        env_file:
            - .env
        ports:
            - "127.0.0.1:8444:8444"
            - "127.0.0.1:15024:15024"
        networks:
            - "internal"
networks:
    internal:
