# SPDX-License-Identifier: MIT

version: "3"
services:
  webui:
    build:
      args:
        - BASE_IMAGE=${BASE_IMAGE}
        - BUILD_TYPE=${BUILD_TYPE}
        - WEBUI_VERSION=${WEBUI_VERSION}
        - JAVA_VERSION=${JAVA_VERSION}
        - TAG=${TAG}
        - BRANCH=${BRANCH}
      context: docker/
      dockerfile: docker/Web-Server-Debian.dockerfile
    container_name: webui
    env_file:
      - .env
      - .env-web-server-server
    ports:
      - "${HOST_NAME}:${WEBUI_PORT}:4443"
      - "${HOST_NAME}:${JAVA_DEBUG_PORT}:15025"
    networks:
      - "internal"

networks:
  internal:
