# SPDX-License-Identifier: MIT

apiVersion: v2
name: pds-iac
description: SecHub PDS + IaC tools as Helm chart for Kubernetes

type: application

maintainers:
  - name: Jeremias Eppler
  - name: Rouven Haertel

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0
