# SPDX-License-Identifier: MIT

version: "3"
services:
    pds-cloc:
        build:
            args:
                - BASE_IMAGE=${BASE_IMAGE}
            context: docker/
            dockerfile: cloc-Debian.dockerfile
        container_name: pds-cloc
        env_file:
            - .env
            - .env-single
        ports:
            - "127.0.0.1:8444:8444"
            - "127.0.0.1:15024:15024"
        networks:
            - "internal"
        volumes:
          - ./docker/scripts:/scripts
networks:
    internal:
