# SPDX-License-Identifier: MIT

version: "3"
services:
    pds-cloc:
        build:
            args:
                - BASE_IMAGE=${BASE_IMAGE}
            context: docker/
            dockerfile: cloc-Debian.dockerfile
        container_name: pds-cloc
        hostname: pds-cloc
        env_file:
            - .env
            - .env-single
        networks:
            - "sechub"
        volumes:
          - ./docker/scripts:/scripts

networks:
    sechub:
        external: true
        name: "sechub"
