# SPDX-License-Identifier: MIT

version: "3"
services:
  pds-owasp-zap-debian:
    build:
      args:
        - BASE_IMAGE=debian:11-slim
      context: docker/
      dockerfile: Owasp-Zap-Debian.dockerfile
    container_name: pds-owasp-zap-debian
    env_file:
      - .env
    ports:
      - "127.0.0.1:8444:8444"
      - "127.0.0.1:15024:15024"
    networks:
      - "sechub"
networks:
  sechub:
    name: "sechub"
