# SPDX-License-Identifier: MIT

version: "3"
services:
    pds-gosec-alpine:
        build:
            args:
                - BASE_IMAGE=alpine:3.14
            context: docker/
            dockerfile: Dockerfile-Alpine
        env_file:
            - .env
        ports:
            - "127.0.0.1:8444:8444"
            - "127.0.0.1:15024:15024"
        networks:
            - "internal"

networks:
    internal: