# SPDX-License-Identifier: MIT
name: Release Checkmarx wrapper

on:
  workflow_dispatch:
    inputs:
      checkmarx-wrapper-version:
        description: Checkmarx-wrapper Version (e.g. 1.0.0)
        required: true
      checkmarx-wrapper-milestone-number:
        description: Checkmarx-wrapper Milestone number (e.g. 91)
        required: true
jobs:
  release-version:
    name: Create Checkmarx-wrapper release
    runs-on: ubuntu-latest
    steps:
      - name: "Show Inputs"
        run: |
          echo "Checkmarx-wrapper '${{ github.event.inputs.checkmarx-wrapper-version }}' - Milestone '${{ github.event.inputs.checkmarx-wrapper-milestone-number }}'"

      - name: Checkout branch master
        uses: actions/checkout@v3
        with:
          ref: master

      # Create temporary local tags, so we build documentation for this tag...
      # The final tag on git server side will be done automatically by the release when the draft is saved as "real" release
      - name: Tag Checkmarx Wrapper version v${{ github.event.inputs.checkmarx-wrapper-version }}-checkmarx-wrapper (temporarily)
        run: git tag v${{ github.event.inputs.checkmarx-wrapper-version }}-checkmarx-wrapper

      # ----------------------
      # Setup + Caching
      # ----------------------
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: gradle

      # ----------------------
      # Create a pull request if license headers are missing
      # ----------------------
      - name: run apply-headers.sh
        id: apply-headers
        run: |
          git config user.name "SecHub release job (github-actions)"
          git config user.email github-actions-sechub@users.noreply.github.com
          ./apply-headers.sh
          git commit -am "SPDX headers added by SecHub release job @github-actions" || true
          COMMITS=`git log --oneline --branches --not --remotes`
          echo "::set-output name=commits::$COMMITS"

      - name: Create a pull request for SPDX license headers
        id: pr_spdx_headers
        if: steps.apply-headers.outputs.commits != ''
        uses: peter-evans/create-pull-request@v4.2.4
        with:
          branch: release-spdx-headers
          branch-suffix: short-commit-hash
          delete-branch: true
          title: '0 - Before checkmarx-wrapper release: Add missing SPDX license headers [auto-generated]'
          body: |
            Auto-generated by Github Actions checkmarx-wrapper release job.

            -> Please review and merge **before** publishing the checkmarx-wrapper release.

      - name: Print PR infos
        if: steps.apply-headers.outputs.commits != ''
        run: |
          echo "Pull Request Number - ${{ steps.pr_spdx_headers.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.pr_spdx_headers.outputs.pull-request-url }}"

      - name: Switch back to master branch
        run: git checkout master

      # -----------------------------------------
      # Build SecHub Checkmarx Wrapper
      # -----------------------------------------
      - name: Build Checkmarx Wrapper
        run: ./gradlew :sechub-wrapper-checkmarx:bootJar

      # -----------------------------------------
      # Upload build artifacts
      # -----------------------------------------
      - name: Inspect GIT status
        if: always()
        run: |
          mkdir build/reports -p
          git status > build/reports/git-status.txt

      - name: Archive GIT status
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: git-status.txt
          path: build/reports/git-status.txt
          retention-days: 14

      - name: Archive Checkmarx Wrapper libs directory
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: sechub-wrapper-checkmarx
          path: sechub-wrapper-checkmarx/build/libs
          retention-days: 14

      - name: Switch back to master branch
        run: git checkout master

      # -----------------------------------------
      # Assert releaseable, so no dirty flags on releases
      # even when all artifact creation parts are done!
      # -----------------------------------------
      - name: Assert releasable
        run: ./gradlew assertReleaseable

      - name: Create Checkmarx Wrapper release
        id: create_checkmarx-wrapper_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ github.event.inputs.checkmarx-wrapper-version }}-checkmarx-wrapper
          commitish: master
          release_name: Checkmarx Wrapper Version ${{ github.event.inputs.checkmarx-wrapper-version }}
          body: |
            Changes in this Release
            - Some minor changes on Checkmarx Wrapper implementation

            For more details please look at [Milestone ${{github.event.inputs.checkmarx-wrapper-milestone-number}}]( https://github.com/mercedes-benz/sechub/milestone/${{github.event.inputs.checkmarx-wrapper-milestone-number}}?closed=1)
          draft: true
          prerelease: false

      # -----------------------------------------
      # Upload release artifacts
      # -----------------------------------------
      - name: Create files and sha256 checksum for Checkmarx Wrapper jar
        run: |
          cd sechub-wrapper-checkmarx/build/libs/
          sha256sum sechub-wrapper-checkmarx-${{ github.event.inputs.checkmarx-wrapper-version }}.jar > sechub-wrapper-checkmarx-${{ github.event.inputs.checkmarx-wrapper-version }}.jar.sha256sum

      - name: Upload asset sechub-wrapper-checkmarx-${{ github.event.inputs.checkmarx-wrapper-version }}.jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_checkmarx-wrapper_release.outputs.upload_url }}
          asset_path: sechub-wrapper-checkmarx/build/libs/sechub-wrapper-checkmarx-${{ github.event.inputs.checkmarx-wrapper-version }}.jar
          asset_name: sechub-wrapper-checkmarx-${{ github.event.inputs.checkmarx-wrapper-version }}.jar
          asset_content_type: application/zip

      - name: Upload asset sechub-wrapper-checkmarx-${{ github.event.inputs.checkmarx-wrapper-version }}.jar.sha256sum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_checkmarx-wrapper_release.outputs.upload_url }}
          asset_path: sechub-wrapper-checkmarx/build/libs/sechub-wrapper-checkmarx-${{ github.event.inputs.checkmarx-wrapper-version }}.jar.sha256sum
          asset_name: sechub-wrapper-checkmarx-${{ github.event.inputs.checkmarx-wrapper-version }}.jar.sha256sum
          asset_content_type: text/plain

      # -----------------------------------------
      # Create release issue
      # -----------------------------------------
      - name: Create Checkmarx Wrapper ${{ github.event.inputs.checkmarx-wrapper-version }} release issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Release Checkmarx Wrapper ${{ github.event.inputs.checkmarx-wrapper-version }}
          body: |
            See [Milestone ${{github.event.inputs.checkmarx-wrapper-milestone-number}}]( https://github.com/mercedes-benz/sechub/milestone/${{github.event.inputs.checkmarx-wrapper-milestone-number}}?closed=1) for details.

            Please close this issue after the release.
          milestone: ${{ github.event.inputs.checkmarx-wrapper-milestone-number }}

      # -----------------------------------------
      # Create a pull request for merging back `master` into `develop`
      # -----------------------------------------
      - name: pull-request master to develop
        id: pr_master_to_develop
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: "master"
          destination_branch: "develop"
          pr_allow_empty: true  # should allow an empty PR, but seems not to work
          pr_title: '2 - After Checkmarx Wrapper release: Merge master back into develop [auto-generated]'
          pr_body: |
            Merge master branch back into develop

            -> Please merge **after** the release has been published.

      - name: Print PR infos
        run: |
          echo "Pull Request Number - ${{ steps.pr_master_to_develop.outputs.pr_number }}"
          echo "Pull Request URL - ${{ steps.pr_master_to_develop.outputs.pr_url }}"
