# SPDX-License-Identifier: MIT
name: Release wrapper for Xray

on:
  workflow_dispatch:
    inputs:
      actor-email:
        description: Insert your email address here. It will be used in the generated pull requests
        required: true
      xray-wrapper-version:
        description: Xray-wrapper Version (e.g. 1.0.0)
        required: true
      xray-wrapper-milestone-number:
        description: Xray-wrapper Milestone number (e.g. 91)
        required: true
jobs:
  release-version:
    name: Create Xray-wrapper release
    runs-on: ubuntu-latest
    steps:
      - name: "Show Inputs"
        run: |
          echo "actor-email: '${{ inputs.actor-email }}'"
          echo "Xray-wrapper '${{ inputs.xray-wrapper-version }}' - Milestone '${{ inputs.xray-wrapper-milestone-number }}'"

      - name: Checkout branch master
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
        with:
          ref: master

      # Create temporary local tags, so we build documentation for this tag...
      # The final tag on git server side will be done automatically by the release when the draft is saved as "real" release
      - name: Tag Xray Wrapper version v${{ inputs.xray-wrapper-version }}-xray-wrapper (temporarily)
        run: git tag v${{ inputs.xray-wrapper-version }}-xray-wrapper

      # ----------------------
      # Setup + Caching
      # ----------------------
      - name: Set up JDK 17
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/gradle-build-action@8baac4c8ef753599f92eeb509c246d09d6250fa6
        with:
          cache-read-only: false

      # ----------------------
      # Create a pull request if license headers are missing
      # ----------------------
      - name: run apply-headers.sh
        id: apply-headers
        run: |
          git config user.name "$GITHUB_TRIGGERING_ACTOR (via github-actions)"
          git config user.email "${{ inputs.actor-email }}"
          ./apply-headers.sh
          git commit -am "SPDX headers added by SecHub release job @github-actions" || true
          COMMITS=`git log --oneline --branches --not --remotes`
          echo "commits=$COMMITS" >> $GITHUB_OUTPUT

      - name: Create a pull request for SPDX license headers
        id: pr_spdx_headers
        if: steps.apply-headers.outputs.commits != ''
        uses: peter-evans/create-pull-request@9153d834b60caba6d51c9b9510b087acf9f33f83
        with:
          branch: release-spdx-headers
          branch-suffix: short-commit-hash
          delete-branch: true
          title: '0 - Before xray-wrapper release: Add missing SPDX license headers [auto-generated]'
          body: |
            Auto-generated by Github Actions xray-wrapper release job.

            -> Please review and merge **before** publishing the xray-wrapper release.

      - name: Print PR infos
        if: steps.apply-headers.outputs.commits != ''
        run: |
          echo "Pull Request Number - ${{ steps.pr_spdx_headers.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.pr_spdx_headers.outputs.pull-request-url }}"

      - name: Switch back to master branch
        run: git checkout master

      # -----------------------------------------
      # Build SecHub Xray Wrapper
      # -----------------------------------------
      - name: Build Xray Wrapper
        run: ./gradlew :sechub-wrapper-xray:buildWrapperXray

      # -----------------------------------------
      # Upload build artifacts
      # -----------------------------------------
      - name: Inspect GIT status
        if: always()
        run: |
          mkdir build/reports -p
          git status > build/reports/git-status.txt

      - name: Archive GIT status
        if: always()
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
        with:
          name: git-status.txt
          path: build/reports/git-status.txt
          retention-days: 14

      - name: Archive Xray Wrapper libs directory
        if: always()
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
        with:
          name: sechub-wrapper-xray
          path: sechub-wrapper-xray/build/libs
          retention-days: 14

      - name: Switch back to master branch
        run: git checkout master

      # -----------------------------------------
      # Assert releaseable, so no dirty flags on releases
      # even when all artifact creation parts are done!
      # -----------------------------------------
      - name: Assert releasable
        run: ./gradlew assertReleaseable

      - name: Create Xray Wrapper release
        id: create_xray-wrapper_release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ inputs.xray-wrapper-version }}-xray-wrapper
          commitish: master
          release_name: Xray Wrapper Version ${{ inputs.xray-wrapper-version }}
          body: |
            Changes in this Release
            - Some minor changes on Xray Wrapper implementation

            For more details please look at [Milestone ${{inputs.xray-wrapper-milestone-number}}]( https://github.com/mercedes-benz/sechub/milestone/${{inputs.xray-wrapper-milestone-number}}?closed=1)
          draft: true
          prerelease: false

      # -----------------------------------------
      # Upload release artifacts
      # -----------------------------------------
      - name: Create files and sha256 checksum for Xray Wrapper jar
        run: |
          cd sechub-wrapper-xray/build/libs/
          sha256sum sechub-pds-wrapper-xray-${{ inputs.xray-wrapper-version }}.jar > sechub-pds-wrapper-xray-${{ inputs.xray-wrapper-version }}.jar.sha256sum

      - name: Upload asset sechub-pds-wrapper-xray-${{ inputs.xray-wrapper-version }}.jar
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_xray-wrapper_release.outputs.upload_url }}
          asset_path: sechub-wrapper-xray/build/libs/sechub-pds-wrapper-xray-${{ inputs.xray-wrapper-version }}.jar
          asset_name: sechub-pds-wrapper-xray-${{ inputs.xray-wrapper-version }}.jar
          asset_content_type: application/zip

      - name: Upload asset sechub-pds-wrapper-xray-${{ inputs.xray-wrapper-version }}.jar.sha256sum
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_xray-wrapper_release.outputs.upload_url }}
          asset_path: sechub-wrapper-xray/build/libs/sechub-pds-wrapper-xray-${{ inputs.xray-wrapper-version }}.jar.sha256sum
          asset_name: sechub-pds-wrapper-xray-${{ inputs.xray-wrapper-version }}.jar.sha256sum
          asset_content_type: text/plain

      # -----------------------------------------
      # Create release issue
      # -----------------------------------------
      - name: Create Xray Wrapper ${{ inputs.xray-wrapper-version }} release issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Release Xray Wrapper ${{ inputs.xray-wrapper-version }}
          body: |
            See [Milestone ${{inputs.xray-wrapper-milestone-number}}]( https://github.com/mercedes-benz/sechub/milestone/${{inputs.xray-wrapper-milestone-number}}?closed=1) for details.

            Please close this issue after the release.
          milestone: ${{ inputs.xray-wrapper-milestone-number }}

      # -----------------------------------------
      # Create a pull request for merging back `master` into `develop`
      # -----------------------------------------
      - name: pull-request master to develop
        id: pr_master_to_develop
        continue-on-error: true
        uses: repo-sync/pull-request@7e79a9f5dc3ad0ce53138f01df2fad14a04831c5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: "master"
          destination_branch: "develop"
          pr_allow_empty: true  # should allow an empty PR, but seems not to work
          pr_title: '2 - After Xray Wrapper release: Merge master back into develop [auto-generated]'
          pr_body: |
            Merge master branch back into develop

            -> Please merge **after** the release has been published.

      - name: Print PR infos if PR was created
        if: steps.pr_master_to_develop.outcome == 'success'
        run: |
          echo "Pull Request Number - ${{ steps.pr_master_to_develop.outputs.pr_number }}"
          echo "Pull Request URL - ${{ steps.pr_master_to_develop.outputs.pr_url }}"

      - name: Print info if no PR was created
        if: steps.pr_master_to_develop.outcome != 'success'
        run: |
          echo "Nothing to merge - no pull request necessary."
